name: 'Security Checks: Detect Secrets + Semgrep SAST'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets scan
        id: secrets_scan
        run: |
          detect-secrets scan --all-files > secrets.json

      - name: Upload secrets scan results as artifact
        uses: actions/upload-artifact@main
        with:
          name: secrets-scan-results
          path: secrets.json

  semgrep-sast:
    name: semgrep/ci
    runs-on: ubuntu-latest
    needs: detect-secrets  # Este job depende de la ejecución del job detect-secrets
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - uses: actions/checkout@v4
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
