name: 'Detect Secrets Action'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets scan
        id: secrets_scan
        run: |
          detect-secrets --scan . --json > secrets.json

      - name: Upload secrets scan results as artifact
        uses: actions/upload-artifact@main # Usar versión específica
        with:
          name: secrets-scan-results
          path: secrets.json
