name: 'Security Checks: Detect Secrets + Semgrep SAST'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets scan
        id: secrets_scan
        run: |
          detect-secrets scan --all-files > secrets.json

      - name: Upload secrets scan results as artifact
        uses: actions/upload-artifact@vmain
        with:
          name: secrets-scan-results
          path: secrets.json

      - name: Set up Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: ".semgrep.yml"  # Si usas un archivo de reglas personalizado

      - name: Run Semgrep SAST scan
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        with:
          fail-on: error  # Hace que el build falle si se encuentran errores de severidad ERROR o WARNING
