name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: JuanMorales1025
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        id: repo_owner
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Extract commit SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/JuanMorales1025/bankingsystem:latest
            ghcr.io/JuanMorales1025/bankingsystem:${{ steps.vars.outputs.sha_short }}

      - name: Done
        run: echo "Image pushed to ghcr.io/${{ steps.repo_owner.outputs.owner_lc }}/bankingsystem"
